/*!
 * jQuery Migrate - v1.0.0 - 2013-01-14
 * https://github.com/jquery/jquery-migrate
 * Copyright 2005, 2013 jQuery Foundation, Inc. and other contributors; Licensed MIT
 */
(function(b,x,l){function g(a){p[a]||(p[a]=!0,b.migrateWarnings.push(a),x.console&&console.warn&&!b.migrateMute&&console.warn("JQMIGRATE: "+a))}function m(a,c,d,f){if(Object.defineProperty)try{Object.defineProperty(a,c,{configurable:!0,enumerable:!0,get:function(){g(f);return d},set:function(a){g(f);d=a}});return}catch(e){}b._definePropertyBroken=!0;a[c]=d}var p={};b.migrateWarnings=[];b.migrateReset=function(){p={};b.migrateWarnings.length=0};"BackCompat"===document.compatMode&&g("jQuery is not compatible with Quirks Mode");
var y=b.attr,z=b.attrHooks.value&&b.attrHooks.value.get||function(){return null},A=b.attrHooks.value&&b.attrHooks.value.set||function(){return l},B=/^(?:input|button)$/i,C=/^[238]$/,D=/^(?:autofocus|autoplay|async|checked|controls|defer|disabled|hidden|loop|multiple|open|readonly|required|scoped|selected)$/i,E=/^(?:checked|selected)$/i;m(b,"attrFn",{},"jQuery.attrFn is deprecated");b.attr=function(a,c,d,f){var e=c.toLowerCase(),h=a&&a.nodeType;if(f&&(g("jQuery.fn.attr( props, pass ) is deprecated"),
a&&!C.test(h)&&b.isFunction(b.fn[c])))return b(a)[c](d);"type"===c&&d!==l&&B.test(a.nodeName)&&g("Can't change the 'type' of an input or button in IE 6/7/8");!b.attrHooks[e]&&D.test(e)&&(b.attrHooks[e]={get:function(a,c){var d,e=b.prop(a,c);return!0===e||"boolean"!==typeof e&&(d=a.getAttributeNode(c))&&!1!==d.nodeValue?c.toLowerCase():l},set:function(a,c,d){!1===c?b.removeAttr(a,d):(c=b.propFix[d]||d,c in a&&(a[c]=!0),a.setAttribute(d,d.toLowerCase()));return d}},E.test(e)&&g("jQuery.fn.attr("+e+
") may use property instead of attribute"));return y.call(b,a,c,d)};b.attrHooks.value={get:function(a,b){var d=(a.nodeName||"").toLowerCase();if("button"===d)return z.apply(this,arguments);"input"!==d&&"option"!==d&&g("property-based jQuery.fn.attr('value') is deprecated");return b in a?a.value:null},set:function(a,b){var d=(a.nodeName||"").toLowerCase();if("button"===d)return A.apply(this,arguments);"input"!==d&&"option"!==d&&g("property-based jQuery.fn.attr('value', val) is deprecated");a.value=
b}};var n,k,q=b.fn.init,F=/^(?:.*(<[\w\W]+>)[^>]*|#([\w\-]*))$/;b.fn.init=function(a,c,d){var f;return a&&"string"===typeof a&&!b.isPlainObject(c)&&(f=F.exec(a))&&f[1]&&("<"!==a.charAt(0)&&g("$(html) HTML strings must start with '<' character"),c&&c.context&&(c=c.context),b.parseHTML)?q.call(this,b.parseHTML(b.trim(a),c,!0),c,d):q.apply(this,arguments)};b.fn.init.prototype=b.fn;b.uaMatch=function(a){a=a.toLowerCase();a=/(chrome)[ \/]([\w.]+)/.exec(a)||/(webkit)[ \/]([\w.]+)/.exec(a)||/(opera)(?:.*version|)[ \/]([\w.]+)/.exec(a)||
/(msie) ([\w.]+)/.exec(a)||0>a.indexOf("compatible")&&/(mozilla)(?:.*? rv:([\w.]+)|)/.exec(a)||[];return{browser:a[1]||"",version:a[2]||"0"}};n=b.uaMatch(navigator.userAgent);k={};n.browser&&(k[n.browser]=!0,k.version=n.version);k.chrome?k.webkit=!0:k.webkit&&(k.safari=!0);b.browser=k;m(b,"browser",k,"jQuery.browser is deprecated");b.sub=function(){function a(b,c){return new a.fn.init(b,c)}b.extend(!0,a,this);a.superclass=this;a.fn=a.prototype=this();a.fn.constructor=a;a.sub=this.sub;a.fn.init=function(d,
f){f&&f instanceof b&&!(f instanceof a)&&(f=a(f));return b.fn.init.call(this,d,f,c)};a.fn.init.prototype=a.fn;var c=a(document);g("jQuery.sub() is deprecated");return a};var G=b.fn.data;b.fn.data=function(a){var c,d;return!(d=this[0])||"events"!==a||1!==arguments.length||(c=b.data(d,a),d=b._data(d,a),c!==l&&c!==d||d===l)?G.apply(this,arguments):(g("Use of jQuery.fn.data('events') is deprecated"),d)};var H=/\/(java|ecma)script/i,I=b.fn.andSelf||b.fn.addBack,r=b.buildFragment;b.fn.andSelf=function(){g("jQuery.fn.andSelf() replaced by jQuery.fn.addBack()");
return I.apply(this,arguments)};b.clean||(b.clean=function(a,c,d,f){c=c||document;c=!c.nodeType&&c[0]||c;c=c.ownerDocument||c;g("jQuery.clean() is deprecated");var e,h=[];b.merge(h,b.buildFragment(a,c).childNodes);if(d)for(c=function(a){if(!a.type||H.test(a.type))return f?f.push(a.parentNode?a.parentNode.removeChild(a):a):d.appendChild(a)},a=0;null!=(e=h[a]);a++)b.nodeName(e,"script")&&c(e)||(d.appendChild(e),"undefined"!==typeof e.getElementsByTagName&&(e=b.grep(b.merge([],e.getElementsByTagName("script")),
c),h.splice.apply(h,[a+1,0].concat(e)),a+=e.length));return h});b.buildFragment=function(a,c,d,f){var e;c=c||document;c=!c.nodeType&&c[0]||c;c=c.ownerDocument||c;try{e=r.call(b,a,c,d,f)}catch(h){e=r.call(b,a,c.nodeType?[c]:c[0],d,f),g("jQuery.buildFragment() is deprecated")}e.fragment||(m(e,"fragment",e,"jQuery.buildFragment() is deprecated"),m(e,"cacheable",!1,"jQuery.buildFragment() is deprecated"));return e};var J=b.event.add,K=b.event.remove,L=b.event.trigger,M=b.fn.toggle,s=b.fn.live,t=b.fn.die,
u=/\b(?:ajaxStart|ajaxStop|ajaxSend|ajaxComplete|ajaxError|ajaxSuccess)\b/,v=/(?:^|\s)hover(\.\S+|)\b/,w=function(a){if("string"!=typeof a||b.event.special.hover)return a;v.test(a)&&g("'hover' pseudo-event is deprecated, use 'mouseenter mouseleave'");return a&&a.replace(v,"mouseenter$1 mouseleave$1")};b.event.props&&"attrChange"!==b.event.props[0]&&b.event.props.unshift("attrChange","attrName","relatedNode","srcElement");m(b.event,"handle",b.event.dispatch,"jQuery.event.handle is undocumented and deprecated");
b.event.add=function(a,b,d,f,e){a!==document&&u.test(b)&&g("AJAX events should be attached to document: "+b);J.call(this,a,w(b||""),d,f,e)};b.event.remove=function(a,b,d,f,e){K.call(this,a,w(b)||"",d,f,e)};b.fn.error=function(){var a=Array.prototype.slice.call(arguments,0);g("jQuery.fn.error() is deprecated");a.splice(0,0,"error");if(arguments.length)return this.bind.apply(this,a);this.triggerHandler.apply(this,a);return this};b.fn.toggle=function(a,c){if(!b.isFunction(a)||!b.isFunction(c))return M.apply(this,
arguments);g("jQuery.fn.toggle(handler, handler...) is deprecated");var d=arguments,f=a.guid||b.guid++,e=0,h=function(c){var f=(b._data(this,"lastToggle"+a.guid)||0)%e;b._data(this,"lastToggle"+a.guid,f+1);c.preventDefault();return d[f].apply(this,arguments)||!1};for(h.guid=f;e<d.length;)d[e++].guid=f;return this.click(h)};b.fn.live=function(a,c,d){g("jQuery.fn.live() is deprecated");if(s)return s.apply(this,arguments);b(this.context).on(a,this.selector,c,d);return this};b.fn.die=function(a,c){g("jQuery.fn.die() is deprecated");
if(t)return t.apply(this,arguments);b(this.context).off(a,this.selector||"**",c);return this};b.event.trigger=function(a,b,d,f){!d&!u.test(a)&&g("Global events are undocumented and deprecated");return L.call(this,a,b,d||document,f)};b.each("ajaxStart ajaxStop ajaxSend ajaxComplete ajaxError ajaxSuccess".split(" "),function(a,c){b.event.special[c]={setup:function(){var a=this;a!==document&&(b.event.add(document,c+"."+b.guid,function(){b.event.trigger(c,null,a,!0)}),b._data(this,c,b.guid++));return!1},
teardown:function(){this!==document&&b.event.remove(document,c+"."+b._data(this,c));return!1}}})})(jQuery,window);
jQuery.migrateMute = true
